### ISSUE TITLE
Heap-Buffer-Overflow 

### ISSUE THREAD

**Issue by tylerp96** [marcobambini/gravity#147]
Summary:

Gravity is vulnerable to a Heap-Buffer-Overflow. Attached is the testcase as well as the ASAN and valgrind output. 

Execution Process:

./gravity testcase

```
==19779== Memcheck, a memory error detector
==19779== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==19779== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==19779== Command: ./gravity /home/tylerprice/Desktop/Gravity_Crashes/crashes4/id:001289,sig:11,src:000212+027533,op:splice,rep:2
==19779== 
SEMANTIC ERROR on 0 (8,14): Identifier le not found.
SEMANTIC ERROR on 0 (10,12): Identifier tsue not found.
SEMANTIC ERROR on 0 (12,13): Identifier p not found.
SEMANTIC ERROR on 0 (13,3): Identifier expecu not found.
SEMANTIC ERROR on 0 (15,1): Module mod cannot be declared here.
SEMANTIC ERROR on 0 (16,1): Module mod cannot be declared here.
SEMANTIC ERROR on 0 (18,1): Module mot cannot be declared here.
SEMANTIC ERROR on 0 (20,1): Module mod cannot be declared here.
SEMANTIC ERROR on 0 (22,12): Identifier tsue not found.
SEMANTIC ERROR on 0 (24,13): Identifier p not found.
SEMANTIC ERROR on 0 (25,3): Identifier expecu not found.
SEMANTIC ERROR on 0 (27,1): Module mod cannot be declared here.
SEMANTIC ERROR on 0 (29,12): Identifier tsue not found.
==19779== Invalid read of size 8
==19779==    at 0x41679E: gnode_function_add_upvalue (gravity_ast.c:75)
==19779==    by 0x41099E: lookup_identifier (gravity_semacheck2.c:214)
==19779==    by 0x411EB7: visit_identifier_expr (gravity_semacheck2.c:1032)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x410FBC: visit_postfix_expr (gravity_semacheck2.c:877)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411C29: visit_function_decl (gravity_semacheck2.c:692)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411079: visit_postfix_expr (gravity_semacheck2.c:967)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411955: visit_variable_decl (gravity_semacheck2.c:732)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==  Address 0x5954d10 is 16 bytes after a block of size 112 alloc'd
==19779==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19779==    by 0x416CBD: gnode_module_decl_create (gravity_ast.c:183)
==19779==    by 0x40CF57: parse_module_declaration (gravity_parser.c:1509)
==19779==    by 0x40CF57: parse_declaration_statement (gravity_parser.c:2286)
==19779==    by 0x40B71B: parse_compound_statement (gravity_parser.c:2235)
==19779==    by 0x40B9EF: parse_function (gravity_parser.c:288)
==19779==    by 0x4074F5: parse_precedence (gravity_parser.c:977)
==19779==    by 0x4086E0: parse_expression (gravity_parser.c:1009)
==19779==    by 0x4086E0: parse_arguments_expression (gravity_parser.c:877)
==19779==    by 0x4086E0: parse_postfix_expression (gravity_parser.c:920)
==19779==    by 0x40755C: parse_precedence (gravity_parser.c:997)
==19779==    by 0x40BD9B: parse_expression (gravity_parser.c:1009)
==19779==    by 0x40BD9B: parse_variable_declaration (gravity_parser.c:1272)
==19779==    by 0x40B71B: parse_compound_statement (gravity_parser.c:2235)
==19779==    by 0x40B9EF: parse_function (gravity_parser.c:288)
==19779==    by 0x40C704: parse_function_declaration (gravity_parser.c:1556)
==19779==    by 0x40C704: parse_declaration_statement (gravity_parser.c:2284)
==19779== 
==19779== Invalid write of size 8
==19779==    at 0x416842: gnode_function_add_upvalue (gravity_ast.c:76)
==19779==    by 0x41099E: lookup_identifier (gravity_semacheck2.c:214)
==19779==    by 0x411EB7: visit_identifier_expr (gravity_semacheck2.c:1032)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x410FBC: visit_postfix_expr (gravity_semacheck2.c:877)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411C29: visit_function_decl (gravity_semacheck2.c:692)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411079: visit_postfix_expr (gravity_semacheck2.c:967)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411955: visit_variable_decl (gravity_semacheck2.c:732)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==  Address 0x5954d10 is 16 bytes after a block of size 112 alloc'd
==19779==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19779==    by 0x416CBD: gnode_module_decl_create (gravity_ast.c:183)
==19779==    by 0x40CF57: parse_module_declaration (gravity_parser.c:1509)
==19779==    by 0x40CF57: parse_declaration_statement (gravity_parser.c:2286)
==19779==    by 0x40B71B: parse_compound_statement (gravity_parser.c:2235)
==19779==    by 0x40B9EF: parse_function (gravity_parser.c:288)
==19779==    by 0x4074F5: parse_precedence (gravity_parser.c:977)
==19779==    by 0x4086E0: parse_expression (gravity_parser.c:1009)
==19779==    by 0x4086E0: parse_arguments_expression (gravity_parser.c:877)
==19779==    by 0x4086E0: parse_postfix_expression (gravity_parser.c:920)
==19779==    by 0x40755C: parse_precedence (gravity_parser.c:997)
==19779==    by 0x40BD9B: parse_expression (gravity_parser.c:1009)
==19779==    by 0x40BD9B: parse_variable_declaration (gravity_parser.c:1272)
==19779==    by 0x40B71B: parse_compound_statement (gravity_parser.c:2235)
==19779==    by 0x40B9EF: parse_function (gravity_parser.c:288)
==19779==    by 0x40C704: parse_function_declaration (gravity_parser.c:1556)
==19779==    by 0x40C704: parse_declaration_statement (gravity_parser.c:2284)
==19779== 
==19779== Invalid read of size 8
==19779==    at 0x416893: gnode_function_add_upvalue (gravity_ast.c:93)
==19779==    by 0x41099E: lookup_identifier (gravity_semacheck2.c:214)
==19779==    by 0x411EB7: visit_identifier_expr (gravity_semacheck2.c:1032)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x410FBC: visit_postfix_expr (gravity_semacheck2.c:877)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411C29: visit_function_decl (gravity_semacheck2.c:692)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411079: visit_postfix_expr (gravity_semacheck2.c:967)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==    by 0x411955: visit_variable_decl (gravity_semacheck2.c:732)
==19779==    by 0x401B27: gvisit (gravity_visitor.c:57)
==19779==  Address 0x5954d10 is 16 bytes after a block of size 112 alloc'd
==19779==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19779==    by 0x416CBD: gnode_module_decl_create (gravity_ast.c:183)
==19779==    by 0x40CF57: parse_module_declaration (gravity_parser.c:1509)
==19779==    by 0x40CF57: parse_declaration_statement (gravity_parser.c:2286)
==19779==    by 0x40B71B: parse_compound_statement (gravity_parser.c:2235)
==19779==    by 0x40B9EF: parse_function (gravity_parser.c:288)
==19779==    by 0x4074F5: parse_precedence (gravity_parser.c:977)
==19779==    by 0x4086E0: parse_expression (gravity_parser.c:1009)
==19779==    by 0x4086E0: parse_arguments_expression (gravity_parser.c:877)
==19779==    by 0x4086E0: parse_postfix_expression (gravity_parser.c:920)
==19779==    by 0x40755C: parse_precedence (gravity_parser.c:997)
==19779==    by 0x40BD9B: parse_expression (gravity_parser.c:1009)
==19779==    by 0x40BD9B: parse_variable_declaration (gravity_parser.c:1272)
==19779==    by 0x40B71B: parse_compound_statement (gravity_parser.c:2235)
==19779==    by 0x40B9EF: parse_function (gravity_parser.c:288)
==19779==    by 0x40C704: parse_function_declaration (gravity_parser.c:1556)
==19779==    by 0x40C704: parse_declaration_statement (gravity_parser.c:2284)
==19779== 
SEMANTIC ERROR on 0 (33,3): Identifier expected not found.
SEMANTIC ERROR on 0 (34,4): Identifier expected not found.
SEMANTIC ERROR on 0 (37,1): Identifier modulted not found.
SEMANTIC ERROR on 0 (38,4): Identifier expected not found.
SEMANTIC ERROR on 0 (44,3): Identifier expected not found.
SEMANTIC ERROR on 0 (45,4): Identifier expected not found.
SEMANTIC ERROR on 0 (48,1): Identifier modulted not found.
SEMANTIC ERROR on 0 (49,4): Identifier expected not found.
SEMANTIC ERROR on 0 (52,1): Module mod cannot be declared here.
SEMANTIC ERROR on 0 (54,1): Module mmt cannot be declared here.
SEMANTIC ERROR on 0 (55,17): Identifier expected not found.
==19779== 
==19779== HEAP SUMMARY:
==19779==     in use at exit: 21,744 bytes in 170 blocks
==19779==   total heap usage: 1,434 allocs, 1,264 frees, 96,220 bytes allocated
==19779== 
==19779== LEAK SUMMARY:
==19779==    definitely lost: 13,776 bytes in 137 blocks
==19779==    indirectly lost: 7,968 bytes in 33 blocks
==19779==      possibly lost: 0 bytes in 0 blocks
==19779==    still reachable: 0 bytes in 0 blocks
==19779==         suppressed: 0 bytes in 0 blocks
==19779== Rerun with --leak-check=full to see details of leaked memory
==19779== 
==19779== For counts of detected and suppressed errors, rerun with: -v
==19779== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)


=================================================================
==20538==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60b000003030 at pc 0x000000435dc4 bp 0x7fff57b2dbd0 sp 0x7fff57b2dbc0
READ of size 8 at 0x60b000003030 thread T0
    #0 0x435dc3 in gnode_function_add_upvalue src/compiler/gravity_ast.c:75
    #1 0x42308f in lookup_identifier src/compiler/gravity_semacheck2.c:214
    #2 0x427141 in visit_identifier_expr src/compiler/gravity_semacheck2.c:1032
    #3 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #4 0x4241cb in visit_postfix_expr src/compiler/gravity_semacheck2.c:877
    #5 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #6 0x426984 in visit_function_decl src/compiler/gravity_semacheck2.c:692
    #7 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #8 0x424402 in visit_postfix_expr src/compiler/gravity_semacheck2.c:967
    #9 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #10 0x42605d in visit_variable_decl src/compiler/gravity_semacheck2.c:732
    #11 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #12 0x425b92 in visit_module_decl src/compiler/gravity_semacheck2.c:822
    #13 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #14 0x426984 in visit_function_decl src/compiler/gravity_semacheck2.c:692
    #15 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #16 0x424402 in visit_postfix_expr src/compiler/gravity_semacheck2.c:967
    #17 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #18 0x42605d in visit_variable_decl src/compiler/gravity_semacheck2.c:732
    #19 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #20 0x426984 in visit_function_decl src/compiler/gravity_semacheck2.c:692
    #21 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #22 0x4223b2 in visit_list_stmt src/compiler/gravity_semacheck2.c:514
    #23 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #24 0x427dca in gravity_semacheck2 src/compiler/gravity_semacheck2.c:1113
    #25 0x432dcf in gravity_compiler_run src/compiler/gravity_compiler.c:171
    #26 0x40297e in main src/cli/gravity.c:197
    #27 0x7f906ba0982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #28 0x402c38 in _start (/home/tylerprice/Desktop/Fix_Gravity/gravity/gravity+0x402c38)

0x60b000003030 is located 16 bytes to the right of 112-byte region [0x60b000002fb0,0x60b000003020)
allocated by thread T0 here:
    #0 0x7f906c15379a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x4368fd in gnode_module_decl_create src/compiler/gravity_ast.c:183

SUMMARY: AddressSanitizer: heap-buffer-overflow src/compiler/gravity_ast.c:75 gnode_function_add_upvalue
Shadow bytes around the buggy address:
  0x0c167fff85b0: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c167fff85c0: 00 00 fa fa fa fa fa fa fa fa 00 00 00 00 00 00
  0x0c167fff85d0: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  0x0c167fff85e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa
  0x0c167fff85f0: fa fa fa fa fa fa 00 00 00 00 00 00 00 00 00 00
=>0x0c167fff8600: 00 00 00 00 fa fa[fa]fa fa fa fa fa 00 00 00 00
  0x0c167fff8610: 00 00 00 00 00 00 00 00 00 00 fa fa fa fa fa fa
  0x0c167fff8620: fa fa 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c167fff8630: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c167fff8640: 00 00 00 00 00 00 fa fa fa fa fa fa fa fa 00 00
  0x0c167fff8650: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==20538==ABORTING

```

[testcase.tar.gz](https://github.com/marcobambini/gravity/files/957254/testcase.tar.gz)

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/45f6192cb15a386a151a6676dfd11802fff3d98c.
Modules are not yet supported, so it is better to return an error in this case.
