### ISSUE TITLE
Heap-Buffer-Overflow

### ISSUE THREAD

**Issue by tylerp96** [marcobambini/gravity#149]
Summary:

Gravity is vulnerable to a Heap-Buffer-Overflow. Attached is the testcase, as well as the Valgrind, and ASAN ouput.

```
Execution Process:

./gravity testcase

```
```
ASAN:

=================================================================
==22547==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60b000004840 at pc 0x000000427ab5 bp 0x7fffd0f112f0 sp 0x7fffd0f112e0
READ of size 8 at 0x60b000004840 thread T0
    #0 0x427ab4 in check_class_ivar src/compiler/gravity_semacheck2.c:479
    #1 0x427ab4 in visit_class_decl src/compiler/gravity_semacheck2.c:799
    #2 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #3 0x4223c2 in visit_list_stmt src/compiler/gravity_semacheck2.c:514
    #4 0x402df7 in gvisit src/compiler/gravity_visitor.c:57
    #5 0x427dda in gravity_semacheck2 src/compiler/gravity_semacheck2.c:1113
    #6 0x432ddf in gravity_compiler_run src/compiler/gravity_compiler.c:171
    #7 0x40297e in main src/cli/gravity.c:197
    #8 0x7fb3f295982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x402c38 in _start (/home/tylerprice/Desktop/Fix_Gravity/gravity/gravity+0x402c38)

0x60b000004840 is located 16 bytes to the right of 112-byte region [0x60b0000047c0,0x60b000004830)
allocated by thread T0 here:
    #0 0x7fb3f30a379a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x437084 in gnode_variable_create src/compiler/gravity_ast.c:238

SUMMARY: AddressSanitizer: heap-buffer-overflow src/compiler/gravity_semacheck2.c:479 check_class_ivar
Shadow bytes around the buggy address:
  0x0c167fff88b0: fa fa fa fa fa fa 00 00 00 00 00 00 00 00 00 00
  0x0c167fff88c0: 00 00 00 00 fa fa fa fa fa fa fa fa 00 00 00 00
  0x0c167fff88d0: 00 00 00 00 00 00 00 00 00 00 fa fa fa fa fa fa
  0x0c167fff88e0: fa fa 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c167fff88f0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
=>0x0c167fff8900: 00 00 00 00 00 00 fa fa[fa]fa fa fa fa fa 00 00
  0x0c167fff8910: 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa
  0x0c167fff8920: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c167fff8930: 00 00 fa fa fa fa fa fa fa fa 00 00 00 00 00 00
  0x0c167fff8940: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  0x0c167fff8950: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==22547==ABORTING
```

```
Valgrind:

==22638== Memcheck, a memory error detector
==22638== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==22638== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==22638== Command: ./gravity /home/tylerprice/Desktop/Gravity_Crashes/crashes2/id:000008,sig:11,src:000046,op:ext_AO,pos:464
==22638== 
==22638== Invalid read of size 8
==22638==    at 0x41209C: check_class_ivar (gravity_semacheck2.c:480)
==22638==    by 0x41209C: visit_class_decl (gravity_semacheck2.c:799)
==22638==    by 0x401B27: gvisit (gravity_visitor.c:57)
==22638==    by 0x410451: visit_list_stmt (gravity_semacheck2.c:514)
==22638==    by 0x401B27: gvisit (gravity_visitor.c:57)
==22638==    by 0x41238F: gravity_semacheck2 (gravity_semacheck2.c:1113)
==22638==    by 0x4157E5: gravity_compiler_run (gravity_compiler.c:171)
==22638==    by 0x4017A0: main (gravity.c:197)
==22638==  Address 0x59504b0 is 16 bytes after a block of size 112 alloc'd
==22638==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22638==    by 0x416F14: gnode_variable_create (gravity_ast.c:238)
==22638==    by 0x40DAB9: parser_register_core_classes (gravity_parser.c:2453)
==22638==    by 0x40DAB9: parser_run (gravity_parser.c:2466)
==22638==    by 0x40DAB9: gravity_parser_run (gravity_parser.c:2552)
==22638==    by 0x4157AF: gravity_compiler_run (gravity_compiler.c:161)
==22638==    by 0x4017A0: main (gravity.c:197)
==22638== 
==22638== Invalid read of size 8
==22638==    at 0x41506B: symboltable_lookup (gravity_symboltable.c:115)
==22638==    by 0x4120A7: check_class_ivar (gravity_semacheck2.c:480)
==22638==    by 0x4120A7: visit_class_decl (gravity_semacheck2.c:799)
==22638==    by 0x401B27: gvisit (gravity_visitor.c:57)
==22638==    by 0x410451: visit_list_stmt (gravity_semacheck2.c:514)
==22638==    by 0x401B27: gvisit (gravity_visitor.c:57)
==22638==    by 0x41238F: gravity_semacheck2 (gravity_semacheck2.c:1113)
==22638==    by 0x4157E5: gravity_compiler_run (gravity_compiler.c:171)
==22638==    by 0x4017A0: main (gravity.c:197)
==22638==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==22638== 
==22638== 
==22638== Process terminating with default action of signal 11 (SIGSEGV)
==22638==  Access not within mapped region at address 0x0
==22638==    at 0x41506B: symboltable_lookup (gravity_symboltable.c:115)
==22638==    by 0x4120A7: check_class_ivar (gravity_semacheck2.c:480)
==22638==    by 0x4120A7: visit_class_decl (gravity_semacheck2.c:799)
==22638==    by 0x401B27: gvisit (gravity_visitor.c:57)
==22638==    by 0x410451: visit_list_stmt (gravity_semacheck2.c:514)
==22638==    by 0x401B27: gvisit (gravity_visitor.c:57)
==22638==    by 0x41238F: gravity_semacheck2 (gravity_semacheck2.c:1113)
==22638==    by 0x4157E5: gravity_compiler_run (gravity_compiler.c:171)
==22638==    by 0x4017A0: main (gravity.c:197)
==22638==  If you believe this happened as a result of a stack
==22638==  overflow in your program's main thread (unlikely but
==22638==  possible), you can try to increase the size of the
==22638==  main thread stack using the --main-stacksize= flag.
==22638==  The main thread stack size used in this run was 8388608.
==22638== 
==22638== HEAP SUMMARY:
==22638==     in use at exit: 80,248 bytes in 1,220 blocks
==22638==   total heap usage: 1,247 allocs, 27 frees, 82,541 bytes allocated
==22638== 
==22638== LEAK SUMMARY:
==22638==    definitely lost: 224 bytes in 6 blocks
==22638==    indirectly lost: 1,384 bytes in 17 blocks
==22638==      possibly lost: 0 bytes in 0 blocks
==22638==    still reachable: 78,640 bytes in 1,197 blocks
==22638==         suppressed: 0 bytes in 0 blocks
==22638== Rerun with --leak-check=full to see details of leaked memory
==22638== 
==22638== For counts of detected and suppressed errors, rerun with: -v
==22638== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault
```
[testcase.tar.gz](https://github.com/marcobambini/gravity/files/958947/testcase.tar.gz)

**Comment by marcobambini** [comment]
Very good catch thanks, I forgot to prevent subclassing of core classes (until I'll find out a better way).
Fixed by https://github.com/marcobambini/gravity/commit/e84dce12821189b5a892683e6669f23c90e8f31a.
