### ISSUE TITLE
Double Free (gravity_object_free)

### ISSUE THREAD

**Issue by blindfuzzy** [marcobambini/gravity#153]
Summary:

Gravity is vulnerable to a Double-Free. I have attached the testcase that caused the double-free. This is an issue with the gravity garbage collector again. Here is the past issue submitted by @tylerp96: [https://github.com/marcobambini/gravity/issues/138](url) 

I have listed his fix at the bottom of this. His fix works to solve the double free issue. 

```
Execution:
./gravity -x 
```
ASAN output:
```

==1019==ERROR: AddressSanitizer: attempting double-free on 0x604000003290 in thread T0:
    #0 0x7f7c6c6552ca in __interceptor_free (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x982ca)
    #1 0x43458d in gravity_object_free (/home/robin/gravity_new/gravity/gravity+0x43458d)
    #2 0x417a7e in gravity_gc_cleanup (/home/robin/gravity_new/gravity/gravity+0x417a7e)
    #3 0x422416 in gravity_vm_free (/home/robin/gravity_new/gravity/gravity+0x422416)
    #4 0x401759 in main (/home/robin/gravity_new/gravity/gravity+0x401759)
    #5 0x7f7c6bd0382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x401948 in _start (/home/robin/gravity_new/gravity/gravity+0x401948)

0x604000003290 is located 0 bytes inside of 48-byte region [0x604000003290,0x6040000032c0)
freed by thread T0 here:
    #0 0x7f7c6c6552ca in __interceptor_free (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x982ca)
    #1 0x417a7e in gravity_gc_cleanup (/home/robin/gravity_new/gravity/gravity+0x417a7e)

previously allocated by thread T0 here:
    #0 0x7f7c6c65579a in __interceptor_calloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x9879a)
    #1 0x43486e in gravity_string_to_value (/home/robin/gravity_new/gravity/gravity+0x43486e)

SUMMARY: AddressSanitizer: double-free ??:0 __interceptor_free
==1019==ABORTING

```
Valgrind:

```
==19306== Invalid free() / delete / delete[] / realloc()
==19306==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19306==    by 0x43458D: gravity_object_free (in /home/robin/gravity_new/gravity/gravity)
==19306==    by 0x417A7E: gravity_gc_cleanup (in /home/robin/gravity_new/gravity/gravity)
==19306==    by 0x422416: gravity_vm_free (in /home/robin/gravity_new/gravity/gravity)
==19306==    by 0x401759: main (in /home/robin/gravity_new/gravity/gravity)
==19306==  Address 0x595c8c0 is 0 bytes inside a block of size 48 free'd
==19306==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19306==    by 0x417A7E: gravity_gc_cleanup (in /home/robin/gravity_new/gravity/gravity)
==19306==    by 0x422416: gravity_vm_free (in /home/robin/gravity_new/gravity/gravity)
==19306==    by 0x401759: main (in /home/robin/gravity_new/gravity/gravity)

```
[gravity_object_free_dbl_free.zip](https://github.com/marcobambini/gravity/files/966385/gravity_object_free_dbl_free.zip)

Past fix suggested by @tylerp96:

```
Suggested Fix:

// no filter so free all GC objects
	gravity_object_t *obj = vm->gchead;
	while (obj) {
		gravity_object_t *next = obj->gc.next;
		gravity_object_free(vm, obj);
		--vm->gccount;
		obj = next;
		obj = NULL; // FIX
	}
	vm->gchead = NULL;
```
The fix suggested by @tylerp96 is confirmed to solve the issue.

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/e79b3601f2c9f7ba0bddb834206f3e39632d48fc.

If you set obj to NULL in the GC loop then you break the linked list and you'll end up with a lot of memory leaks. The correct fix is to not free the object if it has been already added to the garbage collector.

**Comment by tylerp96** [comment]
Great fix Marco. Mine was definitely a "hacky" suggestion, but your fix works smooth and looks great.
