### ISSUE TITLE
Double free (gravity_function_free)

### ISSUE THREAD

**Issue by blindfuzzy** [marcobambini/gravity#154]
Summary:

Gravity is vulnerable to a Double-Free. This is an issue with the gravity garbage collector again. Here is the past issue submitted by @tylerp96: [https://github.com/marcobambini/gravity/issues/138](url) 

I have listed his fix at the bottom of this. His fix works to solve the double free issue. 

```
Execution:
./gravity -x 
```
ASAN output:
```
==21790==ERROR: AddressSanitizer: attempting double-free on 0x6040000037d0 in thread T0:
    #0 0x7f262df612ca in __interceptor_free (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x982ca)
    #1 0x432ab8 in gravity_function_free (/home/robin/gravity_new/gravity/gravity+0x432ab8)
    #2 0x417a7e in gravity_gc_cleanup (/home/robin/gravity_new/gravity/gravity+0x417a7e)
    #3 0x422416 in gravity_vm_free (/home/robin/gravity_new/gravity/gravity+0x422416)
    #4 0x401759 in main (/home/robin/gravity_new/gravity/gravity+0x401759)
    #5 0x7f262d60f82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x401948 in _start (/home/robin/gravity_new/gravity/gravity+0x401948)

0x6040000037d0 is located 0 bytes inside of 40-byte region [0x6040000037d0,0x6040000037f8)
freed by thread T0 here:
    #0 0x7f262df612ca in __interceptor_free (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x982ca)
    #1 0x417a7e in gravity_gc_cleanup (/home/robin/gravity_new/gravity/gravity+0x417a7e)

previously allocated by thread T0 here:
    #0 0x7f262df6179a in __interceptor_calloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x9879a)
    #1 0x432af8 in gravity_closure_new (/home/robin/gravity_new/gravity/gravity+0x432af8)

SUMMARY: AddressSanitizer: double-free ??:0 __interceptor_free
==21790==ABORTING
```

Past fix suggested by @tylerp96:

```
Suggested Fix:

// no filter so free all GC objects
	gravity_object_t *obj = vm->gchead;
	while (obj) {
		gravity_object_t *next = obj->gc.next;
		gravity_object_free(vm, obj);
		--vm->gccount;
		obj = next;
		obj = NULL; // FIX
	}
	vm->gchead = NULL;
```

The fix suggested by @tylerp96 is confirmed to solve the issue.

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/e79b3601f2c9f7ba0bddb834206f3e39632d48fc.

If you set obj to NULL in the GC loop then you break the linked list and you'll end up with a lot of memory leaks. The correct fix is to not free the object if it has been already added to the garbage collector.
